spring:
  web:
    resources:
      #启用默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间 单位秒
          max-age: 3600
      chain:
        #资源链中启用缓存，默认启用
        cache: true
        #启用资源链，默认禁用
        enabled: true
        #启用压缩资源(gzip,brotli)解析,默认禁用
        compressed: true
      #静态资源位置
      static-locations: classpath:/static/

  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://39.101.67.172:3306/seckill
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 39.101.67.172
    port: 6379
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  rabbitmq:
    host: 39.101.67.172
    username: admin
    password: admin
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完再继续下一条
        prefetch: 1
        #启动时是否默认启动容器，默认是true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如配2.0的话，第一次等10s，第二次就等20秒，第三次就等40秒
        multiplier: 1


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.javamiaosha.pojo
logging:
  level:
   com.example.javamiaosha: debug