spring:
  web:
    resources:
      #启用默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间 单位秒
          max-age: 3600
      chain:
        #资源链中启用缓存，默认启用
        cache: true
        #启用资源链，默认禁用
        enabled: true
        启用压缩资源(gzip,brotli)解析,默认禁用
        compressed: true
      #静态资源位置
      static-locations: classpath:/static/

  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://39.101.67.172:3306/seckill
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 39.101.67.172
    port: 6379
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.javamiaosha.pojo
logging:
  level:
   com.example.javamiaosha: debug